### PR TITLE
Fix #120 - don't compile in `JsValue` in `proc_macro`.

### LINKED ISSUE #120: Importing `JsValue` in a `proc_macro` causes a compilation error on recent nightly's
Thanks for the crate! I noticed a regression on recent Rust nightly's that causes a linker error when using stylist.

- Rust regression issue: https://github.com/rust-lang/rust/issues/111888

- `JsValue` inclusion: https://github.com/futursolo/stylist-rs/blob/fbd788f0a9a63ccadf6a25e028829a25224140eb/packages/stylist-core/src/error.rs#L19
(this type is later imported by `stylist-macros` but, as far as I know, this variant won't be constructed there)

*I'll work on a PR to see if `JsValue` can be removed for `proc_macro` purposes.*

### PR DESCRIPTION
**Pull request by finnbear**
Fixes #120

If merged, will ultimately require `cargo publish` of new versions for all three crates.

### CODE REVIEW

**Comment by finnbear** [comment]
I incorrectly assumed that enabling a feature in the proc macro wouldn't also enable it in the main (`stylist`) crate. Will use a slightly different approach...

**Comment by futursolo** [comment]
I think this issue has got attention from the compiler team.
I recommend we see if they will prioritise as I do not think regression should make into a release.

If they cannot fix it in a couple days then we can merge this mitigation.

In the meanwhile, would it be possible for you use a nightly version prior to this issue occurring?

**Comment by finnbear** [comment]
> In the meanwhile, would it be possible for you use a nightly version prior to this issue occurring?

Don't worry about me! While I can't change nightly veresions, I have pointed `Cargo.toml` at my github branch and am now up and running.

**Review by futursolo — COMMENTED** [review]
> I incorrectly assumed that enabling a feature in the proc macro wouldn't also enable it in the main (`stylist`) crate. Will use a slightly different approach...
> 
> ... done!

With Rust 1.70, this regression has made into stable. So I think we should mitigate this.

Between the feature approach and target approach, I prefer the feature approach as this would allow others to write code with `Error::Web` without having to write `#[cfg(...)]` and this will disable language server / clippy for native targets.

I was actually able to build individual examples but not the workspace somehow.
Although `cargo build` for the entire workspace should also work as stylist uses cargo resolver 2.

Maybe we can have a mix of both approaches by applying the `#[cfg(feature)]` to `type JsValue`?

**Comment by finnbear** [comment]
> I prefer the feature approach

I initially implemented a feature-based approach but it didn't work for reasons previously described - the feature appeared to be enabled when compiling `stylist`, not just when compiling the `proc-macro` crate.

It sounds like you may have a solution in mind, but I don't fully understand it, so **feel free to fix this issue in whatever way you like in a different PR!**

**Review by universal-git — APPROVED** [review]

**Pull request closed without merging**
