### PR TITLE
Update yew from 0.20 to 0.21

### PR DESCRIPTION
**Pull request by langyo**
18 hours ago :P

All the unit tests were passed and it was built successfully

### CODE REVIEW

**Review by futursolo — APPROVED** [review]
Thanks! Looks good to me.

**Review by futursolo — CHANGES_REQUESTED** [review]
It looks like that CI has failed for some tests. Could you please fix CI?

**Comment by langyo** [comment]
> It looks like that CI has failed for some tests. Could you please fix CI?

Sure, wait a while

**Comment by langyo** [comment]
#142 Oh, a bot
image

**Review by futursolo — APPROVED** [review]
Thanks. Looks good to me.

**Pull request merged**
